# Generated by Django 5.0 on 2024-01-06 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(default='M', max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('birthdate', models.DateField(null=True)),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.CharField(max_length=20, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default='0', max_digits=10)),
                ('status', models.CharField(choices=[('0', 'Required'), ('1', 'Paid')], default='0', max_length=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ecommerce.client')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuantity', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ecommerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ecommerce.product')),
            ],
        ),
    ]
