# Generated by Django 5.0 on 2024-01-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_alter_client_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sex',
            new_name='gender',
        ),
    ]
